---
title: "Logistic Regression"
author: "Johnson Odejide"
date: "2023-04-17"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = T, message = F, warning = F)

library(tidyverse)
```

```{r}
Hours <- c(0.50, 0.75,	1.00,	1.25,	1.50,	1.75,	1.75,	2.00,	2.25,	2.50,	2.75,	3.00,	3.25,	3.50,	4.00,	4.25,	4.50,	4.75,	5.00,	5.50 ) 

Pass <- c(0,	0,	0,	0,	0,	0, 1,	0,	1,	0,	1,	0,	1,	0,	1,	1,	1,	1,	1,	1 )

# length(Hours) # Confirm if it's 20 rows
# length(Pass) # Confirm if it's 20 rows

exam <- data.frame(Hours, Pass)

# Transform the variable Pass to categorical/factor variable.
exam <- mutate(exam, Pass = as.factor(Pass))

# head(exam)

# glimpse(exam)
```

**Fit the Logitistic Regression Model**

```{r}
fit.log <- glm(Pass ~ Hours, family = "binomial", data = exam)

summary(fit.log)
```
**The probability that a student will pass an exam if they study 5.3 hours preparing for it.**

ln(P/(1 - P) =  -4.0777 + 1.5046 * Hours

ln(P/(1 - P) = -4.0777 + 1.5046 * 5.3

ln(P/(1 - P) = 3.89668

e ^ ln(P/(1 - P) = e ^ 3.89668

P / 1 - P = 49.2387

P = 49.2387 (1 - P)

P = 49.2387 - 49.2387P

P + 49.2387P = 49.2387

50.2387P = 49.2387

P = 49.2387 / 50.2387

P = 0.98

_Therefore, the probability that a student will pass an exam if they study 5.3 hours is 0.98._

